# Generated by Django 6.1.1 on 2026-09-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='patient_reports/'),
        ),
    ]
